name: test

on: push

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Hardhat tests
        run: yarn hardhat test --network hardhat

      - name: Run Slither
        uses: crytic/slither-action@v0.2.0
        with:
          ignore-compile: true
          node-version: 16
          fail-on: none